version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend  # Der Pfad zum Dockerfile für das Frontend
    ports:
      - "8080:80"  # Portweiterleitung
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend  # Der Pfad zum Dockerfile für das Backend (optional)
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
